apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution02
  namespace: tenant-example
  labels:
    app: solution02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solution02
  template:
    metadata:
      labels:
        app: solution02
    spec:
      containers:
      - name: solution02
        image: 183070076065.dkr.ecr.us-east-1.amazonaws.com/example-repo:main-0
        env:
        - name: API_CONTEXT 
          valueFrom:
            configMapKeyRef:
              name: solution02
              key: api_context
        - name: API_NAME 
          valueFrom:
            configMapKeyRef:
              name: solution02
              key: api_name
        - name: API_PORT 
          valueFrom:
            configMapKeyRef:
              name: solution02
              key: api_port              
