apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-example-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ConstellationBrands/tenant-example-cd.git
    targetRevision: HEAD
    path: gitops/argo/apps/staging

  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
