apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solution0007-development-staging
  namespace: argocd
  labels:
    app: solution0007
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenant-example
  source:
    repoURL: https://github.com/ConstellationBrands/tenant-example-cd.git
    targetRevision: HEAD
    path: gitops/env/staging/solution0007-development

  destination:
    namespace: tenant-example
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
