apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution03
  namespace: tenant-example
spec:
  template:
    spec:
      serviceAccountName: tenant-example
      containers:
      - name: solution03
        image: 183070076065.dkr.ecr.us-east-1.amazonaws.com/example-repo:main-1628601149
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: solution03-https
  namespace: tenant-example
spec:
  virtualHost:
    domains:
    - 'solution03-dev.sm.ea.sdlc.k8s.cbrands.com'
