apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution0002
  namespace: tenant-example
  labels:
    app: solution0002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solution0002
  template:
    metadata:
      labels:
        app: solution0002
    spec:
      containers:
      - name: solution0002
        image: 558232680640.dkr.ecr.us-east-1.amazonaws.com/example-repo:main-0
        env:
        - name: API_CONTEXT 
          valueFrom:
            configMapKeyRef:
              name: solution0002
              key: api_context
        - name: API_NAME 
          valueFrom:
            configMapKeyRef:
              name: solution0002
              key: api_name
        - name: API_PORT 
          valueFrom:
            configMapKeyRef:
              name: solution0002
              key: api_port              
